import type { Document, Source } from "./types";

// ---------------------------------------------------------------------------
// Demo data — sourced from documents.csv
// In production this is loaded from the database by the API route
// ---------------------------------------------------------------------------

export const DEMO_DOCUMENTS: Document[] = [
  {
    doc_id: "UK-001",
    country: "UK",
    institution_name: "Financial Conduct Authority",
    source_type: "regulator",
    title: "Sustainability Disclosure Requirements (SDR) and Investment Labels",
    document_type: "regulation",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2023-11-28",
    effective_date: "2024-05-31",
    thematic_tags: ["ESG reporting", "Climate disclosure", "Greenwashing"],
    sectors_affected: ["Asset managers", "Financial services"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "FCA-authorised asset managers and investment product providers",
    reporting_threshold: "AUM > £5 billion initially, extended to all in-scope firms by 2025",
    summary:
      "The FCA's SDR regime establishes four sustainability investment labels, introduces anti-greenwashing rules applicable to all FCA-authorised firms from May 2024, and requires detailed sustainability disclosures for retail products. Naming and marketing restrictions take effect from December 2024.",
    confidence_score: 0.97,
    source_url: "https://www.fca.org.uk/publications",
    document_url: "https://www.fca.org.uk/publication/policy/ps23-16.pdf",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "UK-002",
    country: "UK",
    institution_name: "HM Government Policy Portal",
    source_type: "government_portal",
    title: "UK Endorsement of IFRS S1 and IFRS S2 — Consultation on UK Sustainability Reporting Standards",
    document_type: "consultation",
    legal_status: "adopted",
    relevance_class: "high",
    publication_date: "2024-08-05",
    effective_date: "",
    thematic_tags: ["Sustainability reporting", "Climate disclosure", "ESG reporting"],
    sectors_affected: ["Listed companies", "Large private companies"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "UK-listed companies and large public interest entities",
    reporting_threshold: "To be determined following consultation",
    summary:
      "HM Treasury and FRC have opened consultation on the adoption of IFRS S1 and IFRS S2 as the basis for UK Sustainability Reporting Standards. The consultation informs mandatory reporting requirements expected to come into force from 2026.",
    confidence_score: 0.95,
    source_url: "https://www.gov.uk/search/policy-papers-and-consultations",
    document_url:
      "https://www.gov.uk/government/consultations/uk-sustainability-reporting-standards-consultation",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
    is_new: false,
  },
  {
    doc_id: "UK-003",
    country: "UK",
    institution_name: "Financial Conduct Authority",
    source_type: "regulator",
    title: "Climate-related Financial Disclosures — TCFD-aligned Reporting for Listed Companies",
    document_type: "regulation",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2021-12-17",
    effective_date: "2022-01-01",
    thematic_tags: ["Climate disclosure", "ESG reporting", "Corporate governance"],
    sectors_affected: ["Listed companies", "Premium listed issuers"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Companies with a UK premium listing",
    reporting_threshold: "Market capitalisation > £200 million for listed issuers",
    summary:
      "The FCA requires premium listed companies to report in line with the TCFD framework or explain why they have not. Extended to a wider set of issuers in 2022, covering governance, strategy, risk management, and metrics/targets across all four TCFD pillars.",
    confidence_score: 0.96,
    source_url: "https://www.fca.org.uk/publications",
    document_url: "https://www.fca.org.uk/publication/policy/ps21-23.pdf",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "UK-004",
    country: "UK",
    institution_name: "HM Government Policy Portal",
    source_type: "government_portal",
    title: "Green Finance Strategy 2023 — Mobilising Green Investment",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "medium",
    publication_date: "2023-03-30",
    effective_date: "",
    thematic_tags: ["Green finance", "Taxonomy", "Climate disclosure", "Transition planning"],
    sectors_affected: ["Financial services", "All sectors"],
    mandatory_or_voluntary: "voluntary",
    reporting_entities: "All businesses and financial institutions",
    reporting_threshold: "",
    summary:
      "Updated Green Finance Strategy sets out the UK government's plan to make the UK a leading centre for green finance. Confirms mandatory ISSB-aligned reporting timeline, introduces the UK Green Taxonomy consultation roadmap, and outlines Transition Plan Taskforce disclosure work.",
    confidence_score: 0.91,
    source_url: "https://www.gov.uk/search/policy-papers-and-consultations",
    document_url: "https://www.gov.uk/government/publications/green-finance-strategy",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "UK-005",
    country: "UK",
    institution_name: "HM Treasury Legislation Portal",
    source_type: "legislation_portal",
    title: "Environment Act 2021 — Biodiversity Net Gain and Nature Reporting Provisions",
    document_type: "law",
    legal_status: "in_force",
    relevance_class: "medium",
    publication_date: "2021-11-09",
    effective_date: "2024-02-12",
    thematic_tags: ["ESG reporting", "Sustainability reporting"],
    sectors_affected: ["Real estate", "Infrastructure", "Developers"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Developers and land managers subject to planning obligations in England",
    reporting_threshold: "All developments requiring planning permission above minor development threshold",
    summary:
      "Mandates biodiversity net gain of at least 10% for new developments in England. Developers must demonstrate compliance through standardised biodiversity metric and submit biodiversity gain plans. Creates market for biodiversity net gain units.",
    confidence_score: 0.88,
    source_url: "https://www.legislation.gov.uk",
    document_url: "https://www.legislation.gov.uk/ukpga/2021/30",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "UK-006",
    country: "UK",
    institution_name: "HM Government Policy Portal",
    source_type: "government_portal",
    title: "Transition Plan Taskforce Disclosure Framework — Final Recommendations",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "high",
    publication_date: "2023-10-09",
    effective_date: "",
    thematic_tags: ["Transition planning", "Climate disclosure", "ESG reporting"],
    sectors_affected: ["Financial services", "Listed companies", "Large companies"],
    mandatory_or_voluntary: "voluntary",
    reporting_entities: "UK financial institutions and listed companies; mandatory requirements under development",
    reporting_threshold: "",
    summary:
      "The TPT published its final Disclosure Framework setting out expectations for credible, comprehensive transition plans aligned with net zero. The framework covers governance, strategy, risk management, implementation, engagement, and metrics. HMT announced intention to make transition plan disclosures mandatory.",
    confidence_score: 0.93,
    source_url: "https://www.gov.uk/government/organisations/transition-plan-taskforce",
    document_url: "https://transitiontaskforce.net/disclosure-framework/",
    acquisition_method: "feed",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-001",
    country: "Germany",
    institution_name: "Federal Environment Ministry (BMUV)",
    source_type: "ministry",
    title: "Klimaschutzgesetz (KSG) — Federal Climate Change Act Amendment 2023",
    document_type: "law",
    legal_status: "amended",
    relevance_class: "high",
    publication_date: "2023-11-15",
    effective_date: "2024-01-01",
    thematic_tags: ["Climate disclosure", "Emissions reporting", "Transition planning"],
    sectors_affected: ["All sectors", "Energy", "Industry"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Federal government ministries and major emitting sectors",
    reporting_threshold: "Sectoral emission budgets applying to energy, buildings, transport, industry, agriculture, waste",
    summary:
      "The 2023 amendment to Germany's Climate Change Act strengthens sectoral greenhouse gas emission budgets and introduces an 'immediate action programme' requirement when any sector misses its annual target. Sets 2045 net-zero target in law.",
    confidence_score: 0.95,
    source_url: "https://www.bmuv.de/ministerium/gesetze",
    document_url: "https://www.bmuv.de/gesetz/bundes-klimaschutzgesetz",
    acquisition_method: "crawl",
    language_detected: "DE",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-002",
    country: "Germany",
    institution_name: "Bundestag Legislative Database (DIP)",
    source_type: "parliament",
    title: "CSRD-Umsetzungsgesetz — Transposition of EU Corporate Sustainability Reporting Directive",
    document_type: "law",
    legal_status: "proposed",
    relevance_class: "high",
    publication_date: "2024-03-22",
    effective_date: "2024-07-06",
    thematic_tags: ["ESG reporting", "Sustainability reporting", "Climate disclosure", "Corporate governance"],
    sectors_affected: ["Listed companies", "Large companies", "Financial services"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Large companies (>250 employees or >€40M turnover or >€20M balance sheet); listed SMEs from 2026",
    reporting_threshold: "Employee threshold: >250; Revenue threshold: >€40 million turnover",
    summary:
      "Germany's draft legislation transposing the EU CSRD into national law. Requires in-scope companies to report against European Sustainability Reporting Standards (ESRS). Introduces third-party assurance requirement. Expected to affect ~15,000 German companies in first wave.",
    confidence_score: 0.96,
    source_url: "https://dip.bundestag.de",
    document_url: "https://dip.bundestag.de/vorgang/csrd-umsetzungsgesetz/BT-Drucksache-20-12344",
    acquisition_method: "crawl",
    language_detected: "DE",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-003",
    country: "Germany",
    institution_name: "BaFin Financial Regulator",
    source_type: "regulator",
    title: "BaFin Guidance Notice on Dealing with Sustainability Risks",
    document_type: "guidance",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2021-01-13",
    effective_date: "2021-01-13",
    thematic_tags: ["ESG reporting", "Green finance", "Climate disclosure"],
    sectors_affected: ["Banks", "Insurance companies", "Asset managers"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "BaFin-supervised financial institutions (banks, insurers, asset managers)",
    reporting_threshold: "",
    summary:
      "BaFin's Guidance Notice establishes supervisory expectations for how German financial institutions should identify, assess, and manage sustainability risks. Covers governance, strategy, risk management, and disclosure for banks, insurers, and asset managers.",
    confidence_score: 0.94,
    source_url: "https://www.bafin.de",
    document_url:
      "https://www.bafin.de/SharedDocs/Veroeffentlichungen/EN/Merkblatt/mb_210113_nachhaltigkeit_en.html",
    acquisition_method: "crawl",
    language_detected: "EN",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-004",
    country: "Germany",
    institution_name: "Federal Office for Economic Affairs (BAFA)",
    source_type: "regulator",
    title: "Lieferkettensorgfaltspflichtengesetz (LkSG) — Supply Chain Due Diligence Act — Implementing Guidance",
    document_type: "guidance",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2023-01-01",
    effective_date: "2023-01-01",
    thematic_tags: ["Supply chain due diligence", "Human rights disclosure", "ESG reporting"],
    sectors_affected: ["Manufacturing", "Retail", "Automotive", "Technology"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Companies headquartered in Germany with >3,000 employees (2023); extended to >1,000 employees from 2024",
    reporting_threshold: "3,000 employees (2023); 1,000 employees (2024)",
    summary:
      "BAFA implementation guidance for Germany's Supply Chain Due Diligence Act. Companies must establish risk management systems, conduct due diligence on human rights and environmental risks, and publish annual reports. BAFA is the enforcement authority with power to impose fines of up to 2% of global turnover.",
    confidence_score: 0.97,
    source_url: "https://www.bafa.de/DE/Lieferketten/lieferketten_node.html",
    document_url:
      "https://www.bafa.de/SharedDocs/Downloads/DE/Lieferketten/lksg_handreichung.pdf",
    acquisition_method: "crawl",
    language_detected: "DE",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-005",
    country: "Germany",
    institution_name: "Federal Law Gazette (Bundesgesetzblatt)",
    source_type: "official_gazette",
    title: "Energiewirtschaftsgesetz — Amendment on Renewable Energy Reporting",
    document_type: "law",
    legal_status: "amended",
    relevance_class: "medium",
    publication_date: "2023-07-20",
    effective_date: "2023-08-01",
    thematic_tags: ["Emissions reporting", "Green finance", "Transition planning"],
    sectors_affected: ["Energy", "Utilities"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Energy producers and grid operators",
    reporting_threshold: "Applies to all licensed energy market participants",
    summary:
      "Amendment to the Energy Industry Act updates reporting requirements for grid operators and energy producers regarding renewable energy share, emissions intensity, and transition investment disclosure. Aligns with revised EU Electricity Regulation standards.",
    confidence_score: 0.86,
    source_url: "https://www.bgbl.de",
    document_url: "https://www.bgbl.de/xaver/bgbl/start.xav",
    acquisition_method: "crawl",
    language_detected: "DE",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "DE-006",
    country: "Germany",
    institution_name: "Federal Environment Ministry (BMUV)",
    source_type: "ministry",
    title: "German Taxonomy — Sustainable Finance Advisory Committee Recommendations",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "high",
    publication_date: "2024-02-14",
    effective_date: "",
    thematic_tags: ["Taxonomy", "Green finance", "ESG reporting"],
    sectors_affected: ["Financial services", "All sectors"],
    mandatory_or_voluntary: "voluntary",
    reporting_entities: "Financial market participants subject to EU Taxonomy Regulation",
    reporting_threshold: "",
    summary:
      "The German Sustainable Finance Advisory Committee published recommendations on implementation of the EU Taxonomy Regulation in Germany, with particular focus on aligning national industrial policy with taxonomy criteria and proposing transitional provisions for German infrastructure assets.",
    confidence_score: 0.89,
    source_url: "https://www.bmuv.de",
    document_url: "https://www.bmuv.de/sustainable-finance-beirat-empfehlungen-2024",
    acquisition_method: "crawl",
    language_detected: "DE",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
    is_new: false,
  },
  {
    doc_id: "BR-001",
    country: "Brazil",
    institution_name: "Comissão de Valores Mobiliários (CVM)",
    source_type: "regulator",
    title: "CVM Resolution 193 — ESG and Sustainability Disclosure for Listed Companies",
    document_type: "regulation",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2023-08-11",
    effective_date: "2024-01-01",
    thematic_tags: ["ESG reporting", "Climate disclosure", "Sustainability reporting"],
    sectors_affected: ["Listed companies", "Financial services"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Companies listed on Brazilian stock exchanges",
    reporting_threshold: "All listed companies subject to CVM oversight",
    summary:
      "CVM Resolution 193 requires Brazilian listed companies to disclose sustainability information in their annual reference form. Mandates climate-related disclosures following TCFD framework from 2024, with transition provisions for smaller issuers.",
    confidence_score: 0.96,
    source_url: "https://www.gov.br/cvm",
    document_url: "https://conteudo.cvm.gov.br/legislacao/resolucoes/resol193.html",
    acquisition_method: "crawl",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "BR-002",
    country: "Brazil",
    institution_name: "Banco Central do Brasil (BCB)",
    source_type: "central_bank",
    title: "BCB Resolution 4945 — Social Environmental and Climate Policy (PRSAC)",
    document_type: "regulation",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2021-06-25",
    effective_date: "2022-04-01",
    thematic_tags: ["ESG reporting", "Climate disclosure", "Green finance"],
    sectors_affected: ["Banks", "Financial institutions"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "All financial institutions authorised by the Banco Central do Brasil",
    reporting_threshold: "Applies to all BCB-regulated institutions; proportional requirements by size",
    summary:
      "Establishes the Social, Environmental and Climate Policy (PRSAC) framework for Brazilian financial institutions. Requires institutions to implement social, environmental and climate risk management, conduct portfolio-level climate risk assessment, and publish annual sustainability reports.",
    confidence_score: 0.97,
    source_url: "https://www.bcb.gov.br",
    document_url:
      "https://www.bcb.gov.br/estabilidadefinanceira/exibenormativo?tipo=Resolu%C3%A7%C3%A3o%20BCB&numero=4945",
    acquisition_method: "crawl",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "BR-003",
    country: "Brazil",
    institution_name: "Comissão de Valores Mobiliários (CVM)",
    source_type: "regulator",
    title: "CVM Circular — Climate Risk Disclosure Guidance for Investment Funds",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "high",
    publication_date: "2024-03-18",
    effective_date: "2024-07-01",
    thematic_tags: ["Climate disclosure", "ESG reporting", "Green finance"],
    sectors_affected: ["Asset managers", "Investment funds"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "CVM-registered investment fund managers",
    reporting_threshold: "All publicly-offered investment funds",
    summary:
      "CVM guidance circular for investment fund managers on climate-related financial risk disclosure. Establishes minimum disclosure expectations covering physical and transition risk exposure, portfolio carbon metrics, and alignment with net-zero scenarios.",
    confidence_score: 0.92,
    source_url: "https://www.gov.br/cvm",
    document_url: "https://conteudo.cvm.gov.br/legislacao/oficios-circulares/sin/oc-sin-02-2024.html",
    acquisition_method: "crawl",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "BR-004",
    country: "Brazil",
    institution_name: "Ministério do Meio Ambiente (MMA)",
    source_type: "ministry",
    title: "Brazilian Taxonomy — Sustainable Economic Activities Classification System",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "high",
    publication_date: "2024-01-25",
    effective_date: "",
    thematic_tags: ["Taxonomy", "Green finance", "Climate disclosure"],
    sectors_affected: ["Financial services", "All sectors"],
    mandatory_or_voluntary: "voluntary",
    reporting_entities: "Financial institutions and corporates accessing green finance instruments",
    reporting_threshold: "",
    summary:
      "Brazil's Ministry of Finance and MMA launched the Brazilian Taxonomy for sustainable economic activities, drawing on EU Taxonomy methodology but adapted to Brazilian conditions. Covers climate mitigation, climate adaptation, and biodiversity objectives. Open for public consultation.",
    confidence_score: 0.93,
    source_url: "https://www.gov.br/mma",
    document_url:
      "https://www.gov.br/fazenda/pt-br/acesso-a-informacao/acoes-e-programas/financas-sustentaveis/taxonomia-sustentavel-brasileira",
    acquisition_method: "feed",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
    is_new: false,
  },
  {
    doc_id: "BR-005",
    country: "Brazil",
    institution_name: "Imprensa Nacional (Diário Oficial da União)",
    source_type: "official_gazette",
    title: "Decreto 11.550 — Revised National Climate Policy Regulation",
    document_type: "law",
    legal_status: "in_force",
    relevance_class: "high",
    publication_date: "2023-06-05",
    effective_date: "2023-06-05",
    thematic_tags: ["Emissions reporting", "Transition planning", "Climate disclosure"],
    sectors_affected: ["All sectors", "Government"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Federal government agencies and large industrial emitters",
    reporting_threshold: "Applies to federal public administration and regulated industries",
    summary:
      "Presidential decree updates Brazil's National Climate Change Policy regulations in line with updated NDC targets submitted to UNFCCC. Establishes a new Sectoral Mitigation Plans process, updates baseline emissions inventories, and mandates climate risk reporting for federal procurement.",
    confidence_score: 0.91,
    source_url: "https://www.in.gov.br",
    document_url: "https://www.in.gov.br/en/web/dou/-/decreto-n-11.550-de-5-de-junho-de-2023",
    acquisition_method: "crawl",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
  {
    doc_id: "BR-006",
    country: "Brazil",
    institution_name: "Banco Central do Brasil (BCB)",
    source_type: "central_bank",
    title: "BCB — Climate Stress Testing Framework for Financial Institutions",
    document_type: "guidance",
    legal_status: "adopted",
    relevance_class: "medium",
    publication_date: "2023-09-14",
    effective_date: "2024-03-01",
    thematic_tags: ["Climate disclosure", "Green finance", "ESG reporting"],
    sectors_affected: ["Banks", "Financial institutions"],
    mandatory_or_voluntary: "mandatory",
    reporting_entities: "Large Brazilian banks (Tier 1 and Tier 2 under BCB classification)",
    reporting_threshold: "Top 5 largest banks initially; extended to all S1/S2 institutions",
    summary:
      "The BCB published its climate stress testing methodology for supervised financial institutions. Banks must model physical and transition risk scenarios across their loan portfolios and investment books, report results to BCB, and disclose material exposures in annual sustainability reports.",
    confidence_score: 0.93,
    source_url: "https://www.bcb.gov.br",
    document_url:
      "https://www.bcb.gov.br/content/publicacoes/Documents/outras_pub_alfa/stress-test-clima-2023.pdf",
    acquisition_method: "crawl",
    language_detected: "PT",
    requires_human_review: false,
    pipeline_run_date: "2026-03-16",
  },
];

export const COUNTRY_META: Record<string, { flag: string; fullName: string; color: string }> = {
  UK: { flag: "🇬🇧", fullName: "United Kingdom", color: "#3b82f6" },
  Germany: { flag: "🇩🇪", fullName: "Germany", color: "#f59e0b" },
  Brazil: { flag: "🇧🇷", fullName: "Brazil", color: "#10b981" },
};

export function getFilteredDocuments(docs: Document[], filters: Record<string, string>): Document[] {
  return docs.filter((doc) => {
    if (filters.country && filters.country !== "all" && doc.country !== filters.country) return false;
    if (filters.relevance_class && filters.relevance_class !== "all" && doc.relevance_class !== filters.relevance_class) return false;
    if (filters.legal_status && filters.legal_status !== "all" && doc.legal_status !== filters.legal_status) return false;
    if (filters.document_type && filters.document_type !== "all" && doc.document_type !== filters.document_type) return false;
    if (filters.mandatory_or_voluntary && filters.mandatory_or_voluntary !== "all" && doc.mandatory_or_voluntary !== filters.mandatory_or_voluntary) return false;
    if (filters.thematic_tag && filters.thematic_tag !== "all") {
      if (!doc.thematic_tags.some((t) => t.toLowerCase().includes(filters.thematic_tag.toLowerCase()))) return false;
    }
    if (filters.search) {
      const q = filters.search.toLowerCase();
      if (
        !doc.title.toLowerCase().includes(q) &&
        !doc.institution_name.toLowerCase().includes(q) &&
        !doc.summary.toLowerCase().includes(q) &&
        !doc.thematic_tags.join(" ").toLowerCase().includes(q)
      ) return false;
    }
    return true;
  });
}
